---
title: "Alcohol vs Seat choice"
author: "Areli Nava"
date: "summer 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
require(tidyverse)
require(tigerstats)
davisdata <- read.csv(file="UCDavis.csv")
```

```{r eval=FALSE}
davisdata <- davisdata %>%
mutate(across(where(is.character), as.factor))
```

## Our Goal is to answer this question Is there a difference between the alcohol consumed between the row
## you choose to sit in??

## Now with ggplot - first select the basic data

```{r}
library(ggplot2)

# Create the notched box plot with red outliers
ggplot(davisdata, aes(x = Seat, y = alcohol)) +
  geom_boxplot(notch = TRUE, outlier.colour = "red") +
  labs(title = "Notched Box plot by Seat") +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
basicCN <- ggplot(davisdata,aes(y=alcohol,x=Seat))
```
## Now add in boxplot

```{r}
basicCN + geom_boxplot()
```
  
  
### get fancy  

```{r}
basicCN + geom_boxplot(notch=TRUE,outlier.color = "red") + stat_boxplot(geom ='errorbar') + labs(title="Fancy notch boxplot \n with 2 lines")
```

## Numerical Summarys 

## Inferential Tests

## Conclusions


